### ISSUE TITLE
1.19.2 Missing textures

### ISSUE THREAD

**Issue by netcore10** [Phoupraw/CreateSDelightFabricJava#20]
![image](https://github.com/Phoupraw/CreateSDelightFabricJava/assets/181536/89d62543-8866-4fd5-917d-76be7e58dd9a)

**Comment by netcore10** [comment]
Crushed ice, salt, yeast, sweet berries cake, vegetable stew rose mil tea, wheat seeds black tea, iced melon juice.

**Comment by zoi1op** [comment]
Hello, the mod is in alpha release, some blocks / mechanisms will be changed / removed in the future :)

**Comment by netcore10** [comment]
understood! Sorry for the inconvenience.
