### ISSUE TITLE
Crash During Startup

### ISSUE THREAD

**Issue by Joegenco** [Phoupraw/CreateSDelightFabricJava#4]
Minecraft has crashed! net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: me/shedaniel/rei/api/client/gui/widgets/Widget

Caused by: java.lang.NoClassDefFoundError: me/shedaniel/rei/api/client/gui/widgets/Widget

[Crash.log](https://github.com/Phoupraw/CreateSDelightFabricJava/files/10679279/Crash.log)

Game works without this mod. This is the crash when this mod is loaded.

**Comment by Phoupraw** [comment]
I launched game only with create, farmer's delight, fabric api and create's delight, without rei, but game didn't crash. If you launch game only with the mods above, will yours still crash?

**Comment by Joegenco** [comment]
Seems to be fixed now in the latest version -pre6

It runs without problems with:
`  [✔] 3dskinlayers-fabric-1.5.2-mc1.19.1   [✔] ad_astra-fabric-1.19.2-1.12.3   [✔] AdaptiveTooltips-1.0.1-fabric-1.19.2   [✔] Ad-Astra-Giselle-Addon-fabric-1.19.2-1.11   [✔] AdditionalAdditions-5.1.0   [✔] AdditionalStructures-1.19.x-(v.4.1.1)   [✔] AdvancementPlaques-1.19.2-fabric-1.4.6   [✔] advancementsbook-0.7.1   [✔] advdebug-2.3.0   [✔] adventurez-1.4.17   [✔] AE2WTLib-12.8.5   [✔] AEAdditions-1.19.2-4.0.0-fabric   [✔] Allay-In-A-Bottle-1.1.0   [✔] almostunified-fabric-1.19.2-0.3.5   [✔] alternate-current-mc1.19-1.4.0   [✔] AmbientEnvironment-fabric-1.19.2-8.0+3   [✔] AmbientSounds_FABRIC_v5.2.13_mc1.19.2   [✔] amecs-1.3.8+mc.1.19-rc2   [✔] animatica-0.5+1.19   [✔] appleskin-fabric-mc1.19-2.4.1   [✔] Applied-Botanics-1.4.1   [✔] appliedenergistics2-fabric-12.9.2   [✔] architectury-6.5.69-fabric   [✔] ArmorStatues-v4.0.4-1.19.2-Fabric   [✔] audio_engine_tweaks-1.2.2-1.19.build.1   [✔] auditory-0.0.4-1.19.x   [✔] autopath-mc1.19.2-1.4.9   [✔] axolotl-item-fix-1.1.4   [✔] badpackets-fabric-0.2.1   [✔] balm-fabric-4.5.2+0   [✔] BarteringStation-v4.0.3-1.19.2-Fabric   [✔] BasicEndOres-1.19.2-3.2.0-Fabric   [✔] BasicNetherOres-1.19.2-8.2.0-Fabric   [✔] bclib-2.1.5   [✔] BeaconOverhaul-1.7.3+1.19.2   [✔] beautify-1.1.0+fabric-1.19.2   [✔] BedBenefits-Fabric-1.19.2-9.1.2   [✔] bedspreads-fabric-6.0.0+1.19.2   [✔] beenfo-1.19.1-fabric0.58.5-1.3.3-spigot   [✔] besmirchment-1.19-7   [✔] BetterAdvancements-Fabric-1.19.2-0.3.0.148   [✔] betteranimalsplus-1.19.2-11.0.10-fabric   [✔] BetterAnimationsCollection-v4.0.5-1.19.2-Fabric   [✔] betterbeds-1.2.0   [✔] betterbiomeblend-1.19.0-1.3.6-fabric   [✔] bettercombat-fabric-1.5.5+1.19   [✔] BetterControls-Fabric-1.19+v1.2.3   [✔] better-end-2.1.3   [✔] BetterF3-4.0.0-Fabric-1.19.2   [✔] betterfpsdist-fabric-1.19-2.4   [✔] BetterPingDisplay-Fabric-1.19.2-1.1.1   [✔] BetterRecipes-1.3.0   [✔] betterstats-2.2.1+1.19.2   [✔] betterthanmending-1.3.0   [✔] BetterThirdPerson-Fabric-1.19-1.9.0   [✔] bewitchment-1.19-6   [✔] bewitchmentplus-1.19-9   [✔] biomeinfo-1.19.2-12   [✔] biomemakeover-FABRIC-1.19.2-1.6.2   [✔] Blanket Client tweaks-1.1.2   [✔] bodacious_berries-2.0.7+mc1.19.2   [✔] Bookshelf-Fabric-1.19.2-16.2.17   [✔] Botania-1.19.2-437-FABRIC   [✔] BotanyPots-Fabric-1.19.2-9.0.26   [✔] BotanyPotsTiers-Fabric-1.19.2-3.3.1   [✔] botarium-fabric-1.19.2-1.8.2   [✔] BountifulFabric-4.0.0   [✔] brainierbees-1.3   [✔] bsvsb-3.0.2   [✔] bundle_jumble-1.0.0-mc1.19   [✔] capsey-archeology-1.19.2-0.2.4   [✔] capybara-1.19-2.0.1   [✔] carryon-fabric-1.19.2-2.0.4.6   [✔] catwalks-inc-1.3.1   [✔] cc-restitched-1.101.2   [✔] cem-0.7.1_S8_1.19   [✔] chalk-2.1.0+1.19   [✔] chalk-colorful-addon-2.1.1   [✔] charmofundying-fabric-6.1.1+1.19.2   [✔] chat_heads-0.9.0-fabric-1.19.2   [✔] chatsounds-1.1.7   [✔] chefs-delight-1.0.2-fabric-1.19.2   [✔] cherishedworlds-fabric-6.0.1+1.19.2   [✔] chicken-nerf-1.0.16+MC1.19-1.19.2   [✔] chisel-1.4.7+1.19.2   [✔] chiseled-bricks-1.2-1.19   [✔] chisels-and-bits-fabric-1.3.126   [✔] chunksfadein-v3.0.8-1.19   [✔] Chunky-1.3.38   [✔] CITResewn-1.1.2+1.19.2   [✔] ClearDespawn-fabric-1.19.2-1.1.10   [✔] clickadv-fabric-3.0   [✔] Clumps-fabric-1.19.2-9.0.0+14   [✔] collective-1.19.2-6.43   [✔] colormatic-3.1.2+mc.1.19   [✔] ColouredTooltips-Fabric-1.19.2-18.1.4   [✔] combatroll-fabric-1.1.2+1.19   [✔] comforts-fabric-6.0.3+1.19.2   [✔] compacthelpcommand-1.19.2-2.0   [✔] Companion-1.19.2-fabric-3.2.1   [✔] completeconfig-2.1.0   [✔] connectivity-fabric-1.19.2-3.8   [✔] continuity-2.0.1+1.19   [✔] Controlling-fabric-1.19.2-10.0+7   [✔] CorgiLib-fabric-1.19.2-1.0.0.22   [✔] Cosmetica 1.2.3 1.19.1   [✔] create_crystal_clear-1.0+1.19.2   [✔] createdecofixed-0.1.0   [✔] create-fabric-0.5.0.i-946+1.19.2   [✔] create-renewable-ores-1   [✔] CreateSDelightFabricJava-0.1.0-pre6   [✔] CreativeCore_FABRIC_v2.9.3_mc1.19.2   [✔] CreaturesFromTheSnow-4.1.0+1.19.2   [✔] creeperoverhaul-2.0.6-fabric   [✔] crittersandcompanions-fabric-1.19.2-1.0.3   [✔] crops_love_rain-1.3.0   [✔] cryingghasts-1.19.2-3.0   [✔] ctov-3.1.4   [✔] ctov-bountiful-compat-1.0   [✔] ctov-farmers-delight-compat-1.1   [✔] ctov-more-villagers-compat-1.1   [✔] cultural-delights-fabric-0.14.9+1.19.2   [✔] DamageTilt-1.19-fabric-0.1.2   [✔] dark-loading-screen-1.6.12   [✔] DarkPaintings-Fabric-1.19.2-13.1.5   [✔] DarkUtilities-Fabric-1.19.2-13.1.7   [✔] dawn-3.5.0   [✔] DCCH-2.0+1.17   [✔] deathlog-0.2.11+1.19   [✔] Debugify-2.8.0   [✔] deeperdarker-fabric-1.1.6-fabric   [✔] deepslatecutting-fabric-1.5.0   [✔] despawningeggshatch-1.19.2-4.0   [✔] DisableCustomWorldsAdvice-3.0   [✔] Display Case-fabric-1.19-1.0.3   [✔] dragonfight-fabric-1.19.2-2.7   [✔] Droplight-1.19.2-fabric-1.0.5   [✔] duckling-2.0.8-fabric   [✔] durabilityviewer-1.19.1-fabric0.58.5-1.10.3   [✔] dyablesealanters-0.0.1-1.19.2   [✔] dynamiccrosshair-5.0+1.19.2-fabric   [✔] dynamiccrosshair-compat-3.1+1.19.2   [✔] dynamic-fps-2.2.0   [✔] eating-animation-1.9   [✔] ecologics-fabric-1.19.2-2.1.11   [✔] eden-ring-0.6.4   [✔] effective-1.3   [✔] eldritch-mobs-1.12.10   [✔] elytraslot-fabric-6.1.0+1.19.2   [✔] emotecraft-for-MC1.19.2-2.2.7-b.build.47-fabric   [✔] EnchantmentDescriptions-Fabric-1.19.2-13.0.14   [✔] end-goblin-traders-1.5.1   [✔] enhanced_attack_indicator-1.0.4+1.19   [✔] Enhanced_Celestials-fabric-1.19.2-2.1.0.2   [✔] enhancedblockentities-0.7.2+1.19.2   [✔] entity_texture_features_fabric_1.19.2-4.3.1   [✔] entityculling-fabric-1.5.2-mc1.19   [✔] environmentz-1.3.5   [✔] EquipmentCompare-1.19-fabric-1.3.1   [✔] everycomp-1.19.2-2.2.2-fabric   [✔] exordium-fabric-1.0.2-mc1.19.2   [✔] expandeddelight-0.2.5   [✔] ExplorersCompass-1.19.2-2.2.0-fabric   [✔] ExtendedDrawers-1.3.6+mc.1.19.2   [✔] fabric-api-0.73.2+1.19.2   [✔] fabric-end-remastered-5.2.0   [✔] fabric-language-kotlin-1.9.1+kotlin.1.8.10   [✔] fabric-release-regrowth-1.19-31.1.0   [✔] fabric-seasons-1.4-BETA+1.19   [✔] fabricskyboxes-0.6.2+mc1.19.2   [✔] fabrishot-1.9.1   [✔] factory-blocks-mod-1.0.1+1.19   [✔] fallingleaves-1.13.0+1.19.2   [✔] farmers-delight-fabric-1.19.X-1.3.9   [✔] farmersknives-2.4   [✔] Farmersrespite-Fabric-2.2.4   [✔] Fastload+1.19.2-2.6.11   [✔] ferritecore-5.0.3-fabric   [✔] feytweaks-1.19-1.2.3   [✔] fishontheline-1.19.2-3.0   [✔] FogLooksGoodNow-1.1.1   [✔] forgottengraves-1.19.2-3.0.2   [✔] FoxGlow-1.5.0+fabric1.19.2   [✔] FpsReducer2-fabric-1.19.2-2.1   [✔] frame-0.26.1+1.19-fabric   [✔] friendsandfoes-beekeeperhut-fabric-mc1.19.2-1.2.0   [✔] friendsandfoes-fabric-mc1.19.2-1.6.8   [✔] frostiful-0.4.1   [✔] fsb-interop-1.1.3+mc1.19.2-build.25   [✔] fulleng-fabric-0.2   [✔] geckolib-fabric-1.19-3.1.38   [✔] giacomos_bookshelf1.3.4-1.19.2   [✔] global_packs-fabric-1.19.2-1.14.3.1_fabric   [✔] goblin-traders-1.5.2   [✔] go-fish-1.6.0-1.19.1   [✔] Grass_Overhaul-Fabric-22.10.13   [✔] grizzlybear-1.19.2-1.3   [✔] guarding-1.19.2+2.2.1   [✔] guard-villagers-fabric-1.19.2-1.0.16   [✔] healingcampfire-1.19.2-5.0   [✔] Highlighter-1.19.1-fabric-1.1.4   [✔] HopoBetterMineshaft-1.19-1.1.5b   [✔] HopoBetterRuinedPortals-1.19-1.3.2b   [✔] HopoBetterUnderwaterRuins-1.19-1.1   [✔] HorseBuff-1.19-2.0.1   [✔] horse-stats-vanilla-4.2.2   [✔] hotbarcycle-1.1.0+1.19.2   [✔] Iceberg-1.19.1-fabric-1.0.46   [✔] icepreventscropgrowth-1.19.2-3.0   [✔] illuminations-1.10.11   [✔] ImmediatelyFast-1.1.8+1.19   [✔] immersive_armors-1.5.4+1.19.2-fabric   [✔] immersive_weathering-1.19.2-1.2.7-fabric   [✔] improvedsigns-1.2.0   [✔] indium-1.0.9+mc1.19.2   [✔] integrated-circuit-1.1.1   [✔] interdimensional-map-markers-1.0.2   [✔] InventoryProfilesNext-fabric-1.19-1.9.2   [✔] iris-mc1.19.2-1.5.2   [✔] item-model-fix-1.0.3+1.19   [✔] Jade-1.19.1-fabric-8.7.3   [✔] JadeAddons-1.19.2-fabric-3.0.0   [✔] just-end-anchor-1.0.2-1.19   [✔] Kambrik-4.0-1.19.2   [✔] konkrete_fabric_1.6.0_MC_1.19.1-1.19.2   [✔] krypton-0.2.1   [✔] kubejs-fabric-1902.6.0-build.142   [✔] lambdabettergrass-1.3.0+1.19   [✔] lambdynamiclights-2.2.0+1.19.2   [✔] lazydfu-0.1.3   [✔] lazy-language-loader-0.3.1   [✔] leaves-us-in-peace-1.0.12+MC1.19-1.19.2   [✔] LegendaryTooltips-1.19.2-fabric-1.3.3   [✔] libIPN-fabric-1.19-2.0.2   [✔] lithium-fabric-mc1.19.2-0.10.4   [✔] logicgates-1.3.5   [✔] lootintegrations-fabric-1.19.1-1.7   [✔] lucium-1.5-pre1   [✔] lunade-fastanim-1.5.7   [✔] MainMenuChanger-1.2.0   [✔] make_bubbles_pop-0.0.2-1.19   [✔] malilib-fabric-1.19.2-0.13.0   [✔] manure-1.19.2-2.0   [✔] map-atlases-2.3.1+1.19   [✔] memoryleakfix-1.19.3-0.7.0   [✔] memorysettings-fabric-1.19.2-2.2   [✔] merequester-1.19.2-1.0.3   [✔] minecells-1.3.4   [✔] mini-extras-fabric-1.7.3.2+1.19.2   [✔] minihud-fabric-1.19.2-0.23.3   [✔] MissingWilds-fabric-1.19-1.1.2   [✔] MixinConflictHelper-1.2.0   [✔] mob-captains-v2.0.1   [✔] moderate-loading-screen-1.1.3+1.19   [✔] Modern-Industrialization-1.6.2-beta   [✔] modmenu-4.1.2   [✔] moonlight-1.19.2-2.2.5-fabric   [✔] MoreAchievements-1.19.2-1.0.9   [✔] more-axolotls-1.0.2-1.19   [✔] moreculling-1.19.1-0.16.0   [✔] moremobvariants-1.0.1-1.19.2   [✔] morevillagers-fabric-1.19-4.0.2   [✔] MouseTweaks-fabric-mc1.19-2.22   [✔] moveboats-1.19.2-3.0   [✔] moveminecarts-1.19.2-3.1   [✔] mvs-2.5.10-1.19.2   [✔] mysticalnature-1.8-1.19.2   [✔] naturalist-fabric-2.1.1-1.19.2   [✔] NaturesCompass-1.19.2-2.1.0-fabric   [✔] nethermap-2.0.2-1.19.2   [✔] NethersDelight-1.0.1   [✔] NoChatReports-FABRIC-1.19.2-v1.13.12   [✔] nohostilesaroundcampfire-1.19.2-5.0   [✔] noplayerlabels-2.1.0   [✔] no-resource-pack-warnings-1.0.0   [✔] notenoughanimations-fabric-1.6.2-mc1.19.2   [✔] numismatic-overhaul-0.2.8+1.19   [✔] nutritiousmilk-1.19.2-3.0   [✔] onsoulfire-1.19-2   [✔] overweightfarming-1.19.2-2.0.2-fabric   [✔] owo-lib-0.9.3+1.19   [✔] Patchouli-1.19.2-77-FABRIC   [✔] Pehkui-3.6.3+1.14.4-1.19.3   [✔] Philips-ruins1.19.2-4.5[Fabric]   [✔] PickUpNotifier-v4.2.0-1.19.2-Fabric   [✔] placeableblazerods-1.19.2-3.0   [✔] plasmovoice-fabric-1.19.1-1.2.19   [✔] playertrackingcompass-1.19.2-3.0   [✔] polymorph-fabric-0.46.1+1.19.2   [✔] PresenceFootsteps-1.6.4   [✔] Prism-1.19.2-fabric-1.0.3   [✔] probablychests-0.5.5-1.19.2   [✔] promenade-2.7.1   [✔] puddles-1.2.2   [✔] purpeille-3.2.3+fabric-1.19   [✔] puzzle-1.4.2-1.19   [✔] PuzzlesLib-v4.3.12-1.19.2-Fabric   [✔] radiantgear-fabric-2.0.1+1.19.2   [✔] ratsmischief-1.4.0   [✔] Reaper-1.0.4   [✔] recipe-book-is-pain-0.8.1-1.19.2   [✔] Recipe-Unlocker   [✔] reeses_sodium_options-1.4.9+mc1.19.2-build.67   [✔] replanter-fabric-1.19-1.3   [✔] repurposed_structures_fabric-6.1.3+1.19.2   [✔] rer-2.6.0   [✔] resourcefulconfig-fabric-1.19.2-1.0.18   [✔] resourcefullib-1.1.21   [✔] resourcepackchecker-1.19.2-1.0.0   [✔] revelationary-1.3.0   [✔] rhino-fabric-1902.2.2-build.264   [✔] right-click-harvest-1.2.0+1.19-fabric   [✔] rottencreatures-fabric-1.19.2-1.0.1   [✔] RoughlyEnoughItems-9.1.587   [✔] RoughlyEnoughLootTables-1.19-1.0   [✔] roughly-searchable-2.5.2+1.19.3   [✔] rsls-1.0.1   [✔] servercore-1.3.3-1.19.2   [✔] ShoulderSurfing-Fabric-1.19.2-2.3.0   [✔] show-me-your-skin-1.3.7+1.19   [✔] shulkerboxtooltip-fabric-3.2.2+1.19.2   [✔] Simple+Weapons+1.3.7+-+1.19.2   [✔] simpleshulkerpreview-1.19.x-v2.1   [✔] simplyswords-fabric-1.41.0-1.19.2   [✔] sit-1.19-20   [✔] Skinned Lanterns-fabric-1.19.2-2.0.0   [✔] skiptransitions-1.3.2+1.18.x   [✔] slabstoblocks-1.19.2-0   [✔] smarterfarmers-1.19.2-1.7.1-fabric   [✔] smoothboot-fabric-1.19-1.7.1   [✔] sodium-extra-0.4.16+mc1.19.2-build.90   [✔] sodium-fabric-mc1.19.2-0.4.4+build.18   [✔] soundphysics-fabric-1.19.2-1.0.18   [✔] spectrum-1.6.5-1.19.2-leisure_time   [✔] spectrum-jetpacks-0.0.1   [✔] spelunkery-1.19.2-0.1.10-fabric   [✔] spiceoffabric-1.6.0-beta.2+1.19.2   [✔] spiderstpo-fabric-1.19.2-2.0.3   [✔] spirit-fabric-1.19.2-2.2.3   [✔] spirit-walker-0.1.1+1.19   [✔] sprout-1.4.4-fabric   [✔] starlight-1.1.1+fabric.ae22326   [✔] Strawgolem-fabric-1.19.2-2.0.0-beta.5   [✔] styled-chat-2.0.2+1.19.2   [✔] SuggestionProviderFix-1.0.0   [✔] supplementaries-1.19.2-2.2.46-fabric   [✔] TerraBlender-fabric-1.19.2-2.0.1.136   [✔] The_Graveyard_Biomes_1.6_(FABRIC)_for_1.19.2   [✔] thonkutil-2.15.5+1.19   [✔] ToastManager-1.19.2-1.0.1   [✔] Towns-and-Towers-v.1.10.1-FABRIC-1.19.2   [✔] trinkets-3.4.2   [✔] twigs-2.0.0-beta.9+1.19-fabric   [✔] twilightforest-fabric-1.19.2-4.2.335   [✔] universal_ores-1.4.2   [✔] unofficial-sodium-biome-blending-fix-1.0.1   [✔] unstructured-0.5.3+1.19.2   [✔] vanilla_degus-1.19.x-v1.3.2-fabric   [✔] villagernames-1.19.2-5.1   [✔] vinery-1.1.4   [✔] visuality-0.5.5   [✔] vmp-fabric-mc1.19.2-0.2.0+beta.7.28-all   [✔] voidtotem-fabric-1.19.2-2.1.0   [✔] voidz-1.0.9   [✔] Wabi-Sabi-Structures-1.1.2-Fabric   [✔] wanderingcollector-1.1.3+mc1.19   [✔] waveycapes-fabric-1.3.0-mc1.19.2   [✔] WilderWild-1.1.10-Fabric+1.19.2   [✔] wired-redstone-0.4.15+1.19.2   [✔] wondrouswilds-1.19.2-1.1.6   [✔] wraith-croptosis-1.5.1   [✔] xp_obelisk_additions-0.1.8-r+1.19.2-Fabric   [✔] xp_obelisk-0.4.7-r+1.19.2-Fabric   [✔] YetAnotherConfigLib-2.2.0-for-1.19.2   [✔] yttr-7.638+1.19.2   [✔] YungsApi-1.19.2-Fabric-3.8.2   [✔] YungsBetterDesertTemples-1.19.2-Fabric-2.2.1   [✔] YungsBetterDungeons-1.19.2-Fabric-3.2.1   [✔] YungsBetterMineshafts-1.19.2-Fabric-3.2.0   [✔] YungsBetterOceanMonuments-1.19.2-Fabric-2.1.0   [✔] YungsBetterStrongholds-1.19.2-Fabric-3.2.0   [✔] YungsBetterWitchHuts-1.19.2-Fabric-2.1.0   [✔] YungsBridges-1.19.2-Fabric-3.1.0   [✔] YungsExtras-1.19.2-Fabric-3.1.0   [✔] Zoomify-2.9.0`
