### ISSUE TITLE
Crash when smart drain is manually destroyed and cannot be retrieved with the wrench

### ISSUE THREAD

**Issue by OLDRedstone** [Phoupraw/CreateSDelightFabricJava#5]
Crash in both creative and survive mode

[错误报告-2023-2-10_10.12.25.zip](https://github.com/Phoupraw/CreateSDelightFabricJava/files/10703069/-2023-2-10_10.12.25.zip)

Btw, it is too hard to break with netherite pickaxe

**Comment by OLDRedstone** [comment]
Crash in both creative and survive mode
[错误报告-2023-2-10_10.12.25.zip](https://github.com/Phoupraw/CreateSDelightFabricJava/files/10703061/-2023-2-10_10.12.25.zip)
Btw, it is too hard tobreak with netherite pickaxe

**Comment by Phoupraw** [comment]
~~I can't reproduce the crash. Whatever in creative or survival, it doesn't crash when breaking smart drain.~~

**Comment by Phoupraw** [comment]
please update create to at least 0.5.0.g-851.

**Comment by OLDRedstone** [comment]
it works.
thank you!
